from enum import StrEnum


class PolicyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class EnrollmentStatus(StrEnum):
    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class ClaimStatus(StrEnum):
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    PARTIALLY_APPROVED = "PARTIALLY_APPROVED"
    DENIED = "DENIED"
    PAID = "PAID"
    DISPUTED = "DISPUTED"


class LineItemStatus(StrEnum):
    APPROVED = "APPROVED"
    PARTIALLY_APPROVED = "PARTIALLY_APPROVED"
    DENIED = "DENIED"


class DecisionCode(StrEnum):
    COVERED_FULLY = "COVERED_FULLY"
    PARTIAL_DEDUCTIBLE_APPLIED = "PARTIAL_DEDUCTIBLE_APPLIED"
    PARTIAL_LIMIT_REMAINING = "PARTIAL_LIMIT_REMAINING"
    PARTIAL_DEDUCTIBLE_AND_LIMIT = "PARTIAL_DEDUCTIBLE_AND_LIMIT"
    DENIED_NOT_COVERED = "DENIED_NOT_COVERED"
    DENIED_LIMIT_EXHAUSTED = "DENIED_LIMIT_EXHAUSTED"
    DENIED_DEDUCTIBLE_NOT_MET = "DENIED_DEDUCTIBLE_NOT_MET"


class DisputeStatus(StrEnum):
    OPEN = "OPEN"
